Haievska.sale
Dutko-Diana/project-code-craft pull request #15
Opened 2024-09-09 18:23 UTC by tetiana-haievska

Проставила ширину та додала висоту у .sale-watch-advantages - height: 32px; та  .sale-price-wrap доб height: 32px;
Також для .sale-watch-advantages змінила висоту на height: 34px; у медіа правилі для планшета.

2024-09-09 19:03 UTC, Dutko-Diana requested changes
1. Для .hero-image-container забрати height взагалі
2. Для .catalog-menu-list задати 
   display: flex; 
   flex-direction: column;
   align-items: center;
3. Для .menu-list-opys задати align-self: flex-start;

2024-09-10 07:10 UTC, tetiana-haievska commented
.hero-image-container та .catalog-menu-list зробила. 
А от  .menu-list-opys не знайшла.
Ще повернула анімацію для великого годинника)

2024-09-10 07:37 UTC, tetiana-haievska commented
Для .menu-list-opys задати align-self: flex-start; - також готово)

2024-09-10 12:06 UTC, Dutko-Diana approved these changes
Все працює, приймаю 🥇

2024-09-10 12:06 UTC, merged