Haievska - Sale section
Dutko-Diana/project-code-craft pull request #5
Opened 2024-09-06 16:20 UTC by tetiana-haievska

Прописала код та стилі для мобільної та планшетної версії. Розділ Sale.
Трошки у мене не сходиться масштабування тексту під планшет (.sale-text). Перевірте. будь ласка.
І картинки як мені здалося, не завжди відображаються вірної якості. Треба перевірка.

2024-09-06 18:58 UTC, Dutko-Diana commented
1. В html зробити по одній крапочці в шляхах до картинок
2. .sale-title padding-bottom: 24px; замінити на margin-bottom: 24px; і color можна забрати, бо він по замовчуванню в основних стилях
3. в тегах picture в атрибуті media всюди треба брати значення в дужки, тобто:
media="(min-width: 768px)"
4. Для класу sale-watch-appearance заберіть псевдоклас нот ласт чайлд
5. Виправте wrap на nowrap: 
 .sale-watch-list {
    flex-wrap: nowrap;
}
6. Для .sale-watch-item задайте розміри     
    width: 80px;
    height: 80px;
7. Задайте класи для тегів picture і в стилях задайте їм розміри 
  width: 52px;
  height: 54px;
8. В .sale-big-watch-box теж забрати flex wrap
9. Для великого годинника можна поки що забрати ховер і фокус і відповідно transition
10. Для .sale-watch-describe забрати взагалі max-width: 279px;
11. Забрати для всіх текстів font-family: "Gilroy", sans-serif; бо це за умовчанням
12. Для .sale-prod-tag замінити line-height: 1.3; на line-height: 1.29; як і всюди, де по макету line-height: 1.28571;
13.  Для .sale-text зробити марджин ботом 28, а не 26
14. В <li class="sale-watch-advantages"> вкладіть не спан, а р (параграф) і задати параграфам line-height не 1.3, а 1.33;

ПЛАНШЕТНА ВЕРСІЯ (МЕДІАПРАВИЛО):

1. Для секції змінити верхній падінг на 80 (padding-top: 80px;)
2. Для .sale-title додати margin-bottom: 40px; і забрати нижній падінг повністю
3. Для .sale-watch-item внести зміни в розмірах на:
        width: 132px;
        height: 132px;
4. Для чотирьох picture задати розміри в стилях 96*100
5. Знову для .sale-watch-describe повністю забрати обмеження ширини
6. Для .sale-describe-title змінити width на max-width
7. Для .sale-watch-advantages-text додати line-height: 1.29;

2024-09-06 18:59 UTC, Dutko-Diana requested changes
Всі вимоги щодо змін залишила у коментарі. Загалом - чудова робота!!! 👍

2024-09-07 08:52 UTC, tetiana-haievska commented
Внесла зміни.

2024-09-07 10:12 UTC, Dutko-Diana commented
1. Для .sale-price-wrap поміняти [height](height: 32px;) на padding: 8px 12px;
2. Для .sale-text забрати line-height: 1.29;
3. Для .sale-watch-advantages забрати flex-direction: row; і gap: 4px;
4. і забрати нот ласт чайлд

2024-09-07 10:13 UTC, Dutko-Diana requested changes
Все прекрасно виправлено, тільки три маленькі детальки лишилось)

2024-09-07 10:25 UTC, tetiana-haievska commented
Виконано) Запушила.

2024-09-07 10:30 UTC, Dutko-Diana approved these changes
Чудова робота!

2024-09-07 10:30 UTC, merged